services:
  nginx-test:
    image: nginx
    volumes:
     - ./src/main/dist/templates:/etc/nginx/templates
    ports:
     - "8080:80"
     - "9999:9999"
    environment:
     - J3_INFO_GROUP=me.julb
     - J3_INFO_ARTIFACT=nginx-test
     - J3_INFO_NAME=nginx-test
     - J3_INFO_VERSION=1.0.0
     - J3_IRN=irn-value
     - J3_MONITORING_PORT=9999